# Uncomment this line to define a global platform for your project
# platform :ios, '9.2'
# Uncomment this line if you're using Swift
 use_frameworks!

target 'Mood' do
    pod 'MBProgressHUD', '~> 0.9.2'
    pod 'Realm'
    pod 'Firebase/Core'
    pod 'Firebase/AdMob'
    pod 'Firebase/Crash'
end

target 'MoodWidget' do
    pod 'Realm'
end
